item{
id:1
name:'bag'
}
item{
id:2
name:'ring'
}
item{
id:3
name:'jewellery'
}
item{
id:4
name:'bottle'
}
item{
id:5
name:'model'
}
item{
id:6
name:'spects'
}
item{
id:7
name:'furniture'
}
item{
id:8
name:'Iplastic'
}
item{
id:9
name:'short_box'
}
item{
id:10
name:'kidware'
}
item{
id:11
name:'footwear'
}
item{
id:12
name:'boxes'
}
item{
id:13
name:'shortboxes'
}
item{
id:14
name:'cap'
}
item{
id:15
name:'idol'
}
item{
id:16
name:'tags'
}
item{
id:17
name:'watch'
}